name: Enforce Branch Naming
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch naming convention
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|release|hotfix)/[A-Z]+-[0-9]+-[a-z0-9-]+$ ]]; then
            echo "❌ Branch name does not follow the required format!"
            exit 1
          fi
        shell: bash
